export type Concept =
  | 'reject'
  | 'necessaryOnly'
  | 'manage'
  | 'disableAll'
  | 'object'
  | 'save'
  | 'vendor'
  | 'optionalControl'
  | 'requiredControl'
  | 'legitimateInterest'
  | 'consentContext'
  | 'consentDataContext'
  | 'nonConsentContext'
  | 'unsafePositive';

// Phrases are deliberately separate from behavior. Longer phrases win during classification.
export const LEXICON: Readonly<Record<Concept, readonly string[]>> = {
  reject: [
    'reject all',
    'decline all',
    'disagree',
    'do not accept',
    'deny all',
    'refuse all',
    'tout refuser',
    'alle ablehnen',
    'alles afwijzen',
    'rechazar todo',
    'rifiuta tutto',
    'rejeitar tudo',
    'afvis alle',
  ],
  necessaryOnly: [
    'necessary only',
    'essential only',
    'continue without accepting',
    'nur notwendige',
    'uniquement nécessaires',
    'solo necesarias',
    'solo necessari',
    'alleen noodzakelijk',
  ],
  manage: [
    'manage preferences',
    'manage choices',
    'manage consent',
    'privacy settings',
    'privacy centre',
    'privacy center',
    'cookie settings',
    'cookie banner settings',
    'view vendors',
    'manage vendors',
    'customise',
    'customize',
    'paramètres',
    'einstellungen',
    'preferencias',
    'impostazioni',
    'instellingen',
  ],
  disableAll: [
    'disable all',
    'turn off all',
    'deselect all',
    'tout désactiver',
    'alle deaktivieren',
    'desactivar todo',
    'disattiva tutto',
  ],
  object: [
    'object all',
    'object to all',
    'oppose all',
    'tout refuser',
    'widersprechen',
    'opponerme',
    'bezwaar maken',
  ],
  save: [
    'save choices',
    'save my choices',
    'save and close',
    'save preferences',
    'confirm choices',
    'confirm selection',
    'apply choices',
    'apply settings',
    'enregistrer',
    'speichern',
    'guardar preferencias',
    'salva preferenze',
    'keuzes opslaan',
  ],
  vendor: [
    'vendor',
    'vendors',
    'partner',
    'partners',
    'fournisseur',
    'anbieter',
    'proveedor',
    'fornitore',
    'leverancier',
  ],
  optionalControl: [
    'optional',
    'analytics',
    'measurement',
    'advertising',
    'marketing',
    'personalisation',
    'personalization',
    'social media',
    'facultatif',
    'analyse',
    'werbung',
    'statistik',
    'publicidad',
    'mercadotecnia',
    'pubblicità',
    'advertentie',
  ],
  requiredControl: [
    'strictly necessary',
    'required',
    'essential',
    'security',
    'authentication',
    'strictement nécessaire',
    'nécessaire',
    'unbedingt erforderlich',
    'notwendig',
    'estrictamente necesario',
    'esencial',
    'strettamente necessario',
    'noodzakelijk',
  ],
  legitimateInterest: [
    'legitimate interest',
    'intérêt légitime',
    'berechtigtes interesse',
    'interés legítimo',
    'interesse legittimo',
    'gerechtvaardigd belang',
  ],
  consentContext: [
    'cookie',
    'cookies',
    'cookie choices',
    'cookie preferences',
    'cookie banner',
    'cookie notice',
    'privacy',
    'privacy choices',
    'privacy preferences',
    'consent',
    'consent choices',
    'consent preferences',
    'consent management',
    'tracking',
    'personal data',
    'your data',
    'use your data',
    'how we use your data',
    'we use cookies',
    'we and our partners',
    'données personnelles',
    'datenschutz',
    'privacidad',
    'riservatezza',
    'persoonlijke gegevens',
  ],
  consentDataContext: [
    'cookie',
    'cookies',
    'cookie choices',
    'cookie preferences',
    'tracking',
    'personal data',
    'your data',
    'use your data',
    'how we use your data',
    'data processing',
    'processing purposes',
    'process your data',
    'device storage',
    'device identifiers',
    'online identifiers',
    'store information',
    'store and/or access information',
    'access or store information',
    'access information',
    'advertising purposes',
    'advertising partners',
    'targeted advertising',
    'behavioral advertising',
    'personalized advertising',
    'personalised advertising',
    'analytics cookies',
    'advertising cookies',
    'essential cookies',
    'non-essential cookies',
    'optional cookies',
    'legitimate interest',
    'vendors and partners',
    'third party vendors',
    'privacy choices',
    'privacy preferences',
    'consent choices',
    'consent preferences',
    'consent management',
    'donnÃ©es personnelles',
    'datenschutz',
    'datos personales',
    'dati personali',
    'persoonlijke gegevens',
  ],
  nonConsentContext: [
    'product tour',
    'guided tour',
    'newsletter',
    'subscribe',
    'subscription',
    'sign in',
    'log in',
    'login',
    'account settings',
    'verify your age',
    'age verification',
    'over 18',
    'payment',
    'checkout',
    'notifications',
    'push notifications',
    'location access',
    'camera access',
    'microphone access',
    'survey',
    'feedback',
    'download',
    'install',
    'software update',
    'customer support',
    'live chat',
    'track order',
    'order tracking',
    'delivery updates',
  ],
  unsafePositive: [
    'accept all',
    'accept all cookies',
    'accept selected',
    'accept cookies',
    'agree and continue',
    'agree',
    'i agree',
    'allow all',
    'allow selected',
    'allow partners',
    'recommended',
    'enable all',
    'consent all',
    'tout accepter',
    'alle akzeptieren',
    'aceptar todo',
    'accetta tutto',
    'alles accepteren',
  ],
};
