export type Concept =
  | 'reject'
  | 'necessaryOnly'
  | 'manage'
  | 'disableAll'
  | 'object'
  | 'save'
  | 'vendor'
  | 'optionalControl'
  | 'requiredControl'
  | 'legitimateInterest'
  | 'consentContext'
  | 'consentDataContext'
  | 'nonConsentContext'
  | 'unsafePositive';

// Phrases are deliberately separate from behavior. Longer phrases win during classification.
export const LEXICON: Readonly<Record<Concept, readonly string[]>> = {
  reject: [
    'reject all',
    'decline all',
    'disagree',
    'do not accept',
    'deny all',
    'refuse all',
    'tout refuser',
    'alle ablehnen',
    'alles afwijzen',
    'rechazar todo',
    'rifiuta tutto',
    'rejeitar tudo',
    'afvis alle',
  ],
  necessaryOnly: [
    'necessary only',
    'essential only',
    'continue without accepting',
    'nur notwendige',
    'uniquement nécessaires',
    'solo necesarias',
    'solo necessari',
    'alleen noodzakelijk',
  ],
  manage: [
    'manage preferences',
    'privacy settings',
    'cookie settings',
    'customise',
    'customize',
    'paramètres',
    'einstellungen',
    'preferencias',
    'impostazioni',
    'instellingen',
  ],
  disableAll: [
    'disable all',
    'turn off all',
    'deselect all',
    'tout désactiver',
    'alle deaktivieren',
    'desactivar todo',
    'disattiva tutto',
  ],
  object: [
    'object all',
    'object to all',
    'oppose all',
    'tout refuser',
    'widersprechen',
    'opponerme',
    'bezwaar maken',
  ],
  save: [
    'save choices',
    'save preferences',
    'confirm choices',
    'apply settings',
    'enregistrer',
    'speichern',
    'guardar preferencias',
    'salva preferenze',
    'keuzes opslaan',
  ],
  vendor: [
    'vendor',
    'vendors',
    'partner',
    'partners',
    'fournisseur',
    'anbieter',
    'proveedor',
    'fornitore',
    'leverancier',
  ],
  optionalControl: [
    'optional',
    'analytics',
    'measurement',
    'advertising',
    'marketing',
    'personalisation',
    'personalization',
    'social media',
    'facultatif',
    'analyse',
    'werbung',
    'statistik',
    'publicidad',
    'mercadotecnia',
    'pubblicità',
    'advertentie',
  ],
  requiredControl: [
    'strictly necessary',
    'required',
    'essential',
    'security',
    'authentication',
    'strictement nécessaire',
    'nécessaire',
    'unbedingt erforderlich',
    'notwendig',
    'estrictamente necesario',
    'esencial',
    'strettamente necessario',
    'noodzakelijk',
  ],
  legitimateInterest: [
    'legitimate interest',
    'intérêt légitime',
    'berechtigtes interesse',
    'interés legítimo',
    'interesse legittimo',
    'gerechtvaardigd belang',
  ],
  consentContext: [
    'cookie',
    'cookies',
    'privacy',
    'consent',
    'tracking',
    'personal data',
    'données personnelles',
    'datenschutz',
    'privacidad',
    'riservatezza',
    'persoonlijke gegevens',
  ],
  consentDataContext: [
    'cookie',
    'cookies',
    'tracking',
    'personal data',
    'data processing',
    'process your data',
    'device storage',
    'store information',
    'access information',
    'advertising purposes',
    'legitimate interest',
    'privacy choices',
    'privacy preferences',
    'consent choices',
    'consent preferences',
    'consent management',
    'donnÃ©es personnelles',
    'datenschutz',
    'datos personales',
    'dati personali',
    'persoonlijke gegevens',
  ],
  nonConsentContext: [
    'product tour',
    'guided tour',
    'newsletter',
    'subscribe',
    'subscription',
    'sign in',
    'log in',
    'login',
    'account settings',
    'verify your age',
    'age verification',
    'over 18',
    'payment',
    'checkout',
    'notifications',
    'push notifications',
    'location access',
    'camera access',
    'microphone access',
    'survey',
    'feedback',
    'download',
    'install',
    'software update',
    'customer support',
    'live chat',
    'track order',
    'order tracking',
    'delivery updates',
  ],
  unsafePositive: [
    'accept all',
    'accept selected',
    'agree and continue',
    'agree',
    'allow all',
    'allow partners',
    'recommended',
    'enable all',
    'consent all',
    'tout accepter',
    'alle akzeptieren',
    'aceptar todo',
    'accetta tutto',
    'alles accepteren',
  ],
};
